### PR TITLE
fix: Correct `clangd_extension` setup due to breaking changes

### LINKED ISSUE #103: Clangd configuration no more needed
According to 
https://github.com/p00f/clangd_extensions.nvim/commit/643fd64f908eaa599469cb0af9a204a0dbd3b7e2

the setup 

https://github.com/AstroNvim/docs/blob/787c399601ab2df54be5e60fe9aa0aff34b67082/docs/Recipes/advanced_lsp.md?plain=1#L370

can be ignored and then it works. 

Is the identical now something like?
```lua
  clangd = function(server, opts)
    local lspconfig = require "lspconfig"
    lspconfig[server].setup(opts)
    require("clangd_extensions").setup()
  end,
```

I make a PR

### PR DESCRIPTION
**Pull request by gabyx**
Closes #103 

## 📑 Description

`clangd_extensions` has had some breaking changes. Setup is now different.

I hope my suggestion is correct, I tested it in my setup, seems to work.

### CODE REVIEW

**Review by mehalter — CHANGES_REQUESTED** [review]
This actually can be improved quite a bit and do a full segregation from the idea of the `lsp` settings all together. I think we should probably recommend something like this:

```lua
return {
  lsp = {
    config = {
      clangd = {
        capabilities = {
          offsetEncoding = "utf-8",
        },
      },
    },
  },
  plugins = {
    {
      "p00f/clangd_extensions.nvim",
      init = function()
        local augroup = vim.api.nvim_create_augroup("clangd_extensions", { clear = true })
        vim.api.nvim_create_autocmd("LspAttach", {
          group = augroup,
          desc = "Load clangd_extensions with clangd",
          callback = function(args)
            -- if clangd is attached
            if assert(vim.lsp.get_client_by_id(args.data.client_id)).name == "clangd" then
              require "clangd_extensions" -- load plugin
              vim.api.nvim_del_augroup_by_id(augroup) -- delete autocmd after loading clangd_extensions
            end
          end,
        })
      end,
    },
    {
      "williamboman/mason-lspconfig.nvim",
      opts = {
        ensure_installed = { "clangd" }, -- automatically install lsp
      },
    },
  },
}
```

**Comment by lostystyg** [comment]
I would also like to notice that `clangd_extensions` features are enabled by calling corresponding functions in `on_attach`.  So i would like to see in docs something like this:
```lua

**Comment by lostystyg** [comment]
Also `setup_handler` is not longer even needed, `clangd_extensions` will autoconfigure everything, just need to load the plugin

**Review by mehalter — CHANGES_REQUESTED** [review]
This actually would be better to just not rely on `setup_handlers` at all. We can do this entirely through `LspAttach` autocmd. here is a better approach:

```lua
return {
  lsp = {
    config = {
      clangd = {
        capabilities = {
          offsetEncoding = "utf-8",
        },
      },
    },
  },
  plugins = {
    {
      "p00f/clangd_extensions.nvim", -- install lsp plugin
      init = function()
        -- load clangd extensions when clangd attaches
        local augroup = vim.api.nvim_create_augroup("clangd_extensions", { clear = true })
        vim.api.nvim_create_autocmd("LspAttach", {
          group = augroup,
          desc = "Load clangd_extensions with clangd",
          callback = function(args)
            if assert(vim.lsp.get_client_by_id(args.data.client_id)).name == "clangd" then
              require "clangd_extensions"
              -- add more `clangd` setup here as needed such as loading autocmds
              vim.api.nvim_del_augroup_by_id(augroup)
            end
          end,
        })
      end,
    },
    {
      "williamboman/mason-lspconfig.nvim",
      opts = {
        ensure_installed = { "clangd" }, -- automatically install lsp
      },
    },
  },
}
```

**Comment by gabyx** [comment]
May I ask out of curiosity what `assert()` does? Does it throw an exception.
Where does the `augroup` variable come from? What is it for?

Thanks for the help here.

**Comment by mehalter** [comment]
`assert` here basically tells Lua that we are confident that we will get a non-nil valid from the `get_client_by_id` function which can technically return `nil` if the client id doesn't exist. It just makes the Lua language server happy and no complain that that value could be nil. Maintains our type safety.

The `augroup` variable comes from the first line in the `init` function

```lua
local augroup = vim.api.nvim_create_augroup("clangd_extensions", { clear = true })
```

This is just standard practice when making auto commands in vim. Gives a point to make sure (1) the autocommands in that group aren't defined twice and (2) an easy way to disable the auto commands at runtime if the user wanted to. Just standard practice when maintaining vim auto commands

**Review by mehalter — APPROVED** [review]
I went ahead and finished up this PR and also put it in a stable release.

**Pull request merged**
